use latest Node.js version in GitHub workflow to address TypeScript type stripping in Cypress configuration
```
Your configFile is invalid: /home/runner/work/rhoai-in-kind/rhoai-in-kind/odh-dashboard/frontend/src/__tests__/cypress/cypress.config.ts

It threw an error when required, check the stack trace below:

SyntaxError: Unexpected token ':'
    at compileSourceTextModule (node:internal/modules/esm/utils:346:16)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:316:18)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1371:24)
    at Module._compile (node:internal/modules/cjs/loader:1511:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1096:12)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at loadFile (/home/runner/.cache/Cypress/13.17.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (/home/runner/.cache/Cypress/13.17.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:524:28)
    at EventEmitter.emit (node:domain:489:12)
    at process.<anonymous> (/home/runner/.cache/Cypress/13.17.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:524:28)
    at process.emit (node:domain:489:12)
npm error Lifecycle script `cypress:run` failed with error:
npm error code 1
npm error path /home/runner/work/rhoai-in-kind/rhoai-in-kind/odh-dashboard/frontend
npm error workspace odh-dashboard-frontend@2.0.0
npm error location /home/runner/work/rhoai-in-kind/rhoai-in-kind/odh-dashboard/frontend
npm error command failed
npm error command sh -c cypress run -b chrome --project src/__tests__/cypress --spec '**/workbenches/testWorkbenchCreation.cy.ts'
```