fix opendatahub-tests that requires modelregistry in dsc
```
        py_config["applications_namespace"] = get_dsci_applications_namespace(client=admin_client)
        py_config["model_registry_namespace"] = get_data_science_cluster(
            client=admin_client
>       ).instance.spec.components.modelregistry.registriesNamespace
E       AttributeError: 'NoneType' object has no attribute 'registriesNamespace'
```